W6D5/new_cat_99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only:[:index, :show, :new, :create]
end

W6D5/new_cat_99/app/models/cat.rb
class Cat < ApplicationRecord
  validates :birth_date, :color, :name, :sex, :description, presence: true
end

W6D5/new_cat_99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token  
  # protect_from_forgery unless: -> { request.format.json? }

end

W6D5/new_cat_99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all 
    render :index 
  end

  def show
    # p params
    @cat = Cat.find_by(id: params[:id])
    # p @cat
    # render json: @cat
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    debugger
    @cat = Cat.new(cat_params)
    debugger
    if @cat.save
      redirect_to cat_url(@cat)
    end
  end

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end


end

W6D5/new_cat_99/app/views/cats/index.html.erb
<h1>Index Page</h1>
<ul>
  <% @cats.each do |cat| %>
    <ul>
      <li><%= cat.name %> </li>
      <li><%= cat.color %></li>
      <li><%= cat.birth_date %></li>
      <li><%= cat.sex %></li>
      <li><%= cat.description %></li><br>
    </ul>
  <% end %>
</ul>

W6D5/new_cat_99/app/views/cats/new.html.erb
<h1>New Cat</h1>

<form action="<%= cats_url %>" method="POST">
  <label>Catname: 
    <input type="text" name="cat[name]" value="<%= @cat.name %>">
  </label>
  <br>
  <label>Color: 
    <input type="text" name="cat[color]" value="<%= @cat.color %>">
  </label>
  <br>
  <label>Birthdate: 
    <input type="text" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  </label>
  <br>
  <!-- <div>
    Sex: 
    <%= radio_button_tag 'cat[sex]', 'M' %>
    <label>M</label>
    <%= radio_button_tag 'cat[sex]', 'F' %>
    <label>F</label>
  </div> -->
  <label>Sex: 
    <input type="radio" name="cat[sex]" value="F">   
    <label>F</label>
    <input type="radio" name="cat[sex]" value="M">
    <label>M</label>
  </label>
  <br>
  <label>Description: 
    <textarea name="cat[description]"><%= @cat.description %></textarea>
    <!--<input type="text" name="cat[description]" value="">-->
  </label>
  <br>
  <input type="submit" value="Create cat!">
</form>

W6D5/new_cat_99/app/views/cats/show.html.erb
<h1>Show Page</h1>

<li>Name: <%= @cat.name %> </li>
<li>Color: <%= @cat.color %></li>
<li>Birthdate: <%= @cat.birth_date %></li>
<li>Sex: <%= @cat.sex %></li>
<li>Description: <%= @cat.description %></li>
<br>